#VeinMiner settings
#Thu Oct 01 05:49:50 UTC 2026
sakuraFallAnimationEnabled=true
breakLeavesWithTrees=true
toolDurabilityReserve=0
lowDurabilityWarningSound=false
focusedDropsEnabled=false
shovelEnabled=true
oreEnabled=true
customDurabilityMultiplier=1
shovelRadius=1
treeEnabled=true
customBlockLimit=64
activationTriggerMode=SNEAK_KEY
custom.count=0
toolProtectionEnabled=true
mixedOreMiningEnabled=false
modBreakSoundsEnabled=true
customDifficultyMode=DYNAMIC
